# Generated by Django 6.0.6 on 2026-06-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=15),
        ),
    ]
